
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test-namespace
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
